export const LANGUAGES = [
  { code: 'es', name: 'Espanol' },
  { code: 'en', name: 'Ingles' },
  { code: 'fr', name: 'Frances' },
  { code: 'de', name: 'Aleman' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Portugues' },
  { code: 'pt-BR', name: 'Portugues (Brasil)' },
  { code: 'ru', name: 'Ruso' },
  { code: 'zh', name: 'Chino' },
  { code: 'ja', name: 'Japones' },
  { code: 'ko', name: 'Coreano' },
  { code: 'ar', name: 'Arabe' },
  { code: 'hi', name: 'Hindi' },
  { code: 'nl', name: 'Holandes' },
  { code: 'pl', name: 'Polaco' },
  { code: 'tr', name: 'Turco' },
  { code: 'sv', name: 'Sueco' },
  { code: 'da', name: 'Danes' },
  { code: 'fi', name: 'Finlandes' },
  { code: 'no', name: 'Noruego' },
  { code: 'cs', name: 'Checo' },
  { code: 'el', name: 'Griego' },
  { code: 'he', name: 'Hebreo' },
  { code: 'hu', name: 'Hungaro' },
  { code: 'id', name: 'Indonesio' },
  { code: 'ro', name: 'Rumano' },
  { code: 'sk', name: 'Eslovaco' },
  { code: 'sl', name: 'Esloveno' },
  { code: 'uk', name: 'Ucraniano' },
  { code: 'vi', name: 'Vietnamita' },
  { code: 'th', name: 'Tailandes' },
  { code: 'bg', name: 'Bulgaro' },
  { code: 'ca', name: 'Catalan' },
  { code: 'hr', name: 'Croata' },
  { code: 'et', name: 'Estonio' },
  { code: 'lv', name: 'Leton' },
  { code: 'lt', name: 'Lituano' },
  { code: 'ms', name: 'Malayo' },
  { code: 'nb', name: 'Noruego Bokmal' },
  { code: 'fa', name: 'Persa' },
  { code: 'sr', name: 'Serbio' },
  { code: 'sw', name: 'Suajili' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'bn', name: 'Bengali' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mr', name: 'Marathi' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'ur', name: 'Urdu' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'sq', name: 'Albanes' },
  { code: 'az', name: 'Azerbaiyano' },
  { code: 'be', name: 'Bielorruso' },
  { code: 'bs', name: 'Bosnio' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'ga', name: 'Irlandes' },
  { code: 'is', name: 'Islandes' },
  { code: 'mk', name: 'Macedonio' },
  { code: 'mt', name: 'Maltes' },
  { code: 'ne', name: 'Nepali' },
  { code: 'si', name: 'Cingales' },
  { code: 'tl', name: 'Tagalo' },
  { code: 'uz', name: 'Uzbeko' },
  { code: 'cy', name: 'Gales' },
  { code: 'gl', name: 'Gallego' },
  { code: 'eu', name: 'Euskera' },
];

export function getLanguageName(code) {
  return LANGUAGES.find((l) => l.code === code)?.name || code;
}
